#!/usr/bin/env python3
"""
Donum Dei v0.2 plant scraper.

Generates stub plant JSONs from Wikipedia (DE+EN) and Wikimedia Commons APIs.
- Fetches lead image + license + author from Commons
- Fetches description summaries from both Wikipedias
- Outputs schema-conformant JSON to src/data/plants/<slug>.json
- Downloads images to public/images/plants/<slug>.jpg

Uses/safety/quotes are populated with safe defaults; refine manually after.
"""

import json
import os
import re
import sys
import urllib.parse
import urllib.request
from concurrent.futures import ThreadPoolExecutor, as_completed

UA = "DonumDei/0.2 (educational, personal use; maikelganske913@gmail.com)"
TODAY = "2026-05-17"

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(PROJECT_ROOT, "src", "data", "plants")
IMG_DIR = os.path.join(PROJECT_ROOT, "public", "images", "plants")

# Master list: (slug, latin, de_wiki_title, en_wiki_title, family_de, family_en, family_latin,
#               default_use_form, default_target, default_int_ext, default_active_months,
#               default_harvest_part_de, default_harvest_part_en,
#               default_warnings_de, default_warnings_en, external_only)
# NOTE: defaults are sensible starting points. Curate per plant after generation.
PLANTS = [
    # B
    ("valeriana-officinalis", "Valeriana officinalis", "Echter_Baldrian", "Valeriana_officinalis",
     "Geißblattgewächse", "Honeysuckle family", "Caprifoliaceae",
     "tea", ["sleep", "nerves"], "internal", [9, 10],
     "Wurzelstock (Herbst)", "rhizome (autumn)",
     "Längere Anwendung mit Arzt absprechen. In hohen Dosen Müdigkeit am Morgen möglich.",
     "Consult a physician for prolonged use. High doses may cause morning drowsiness.",
     False),
    ("allium-ursinum", "Allium ursinum", "B%C3%A4rlauch", "Allium_ursinum",
     "Amaryllisgewächse", "Amaryllis family", "Amaryllidaceae",
     "raw", ["digestion", "circulation"], "internal", [3, 4, 5],
     "frische Blätter (Frühjahr)", "fresh leaves (spring)",
     "VERWECHSLUNGSGEFAHR mit giftigen Maiglöckchen- und Herbstzeitlosen-Blättern. Nur sicher bestimmte Pflanzen verwenden.",
     "RISK OF CONFUSION with toxic lily-of-the-valley and meadow saffron leaves. Only use plants identified with certainty.",
     False),
    ("artemisia-vulgaris", "Artemisia vulgaris", "Gew%C3%B6hnlicher_Beifu%C3%9F", "Artemisia_vulgaris",
     "Korbblütler", "Daisy family", "Asteraceae",
     "tea", ["digestion"], "internal", [7, 8, 9],
     "blühendes Kraut", "flowering herb",
     "Während Schwangerschaft meiden. Bei Korbblütler-Allergie meiden.",
     "Avoid during pregnancy. Avoid in case of Asteraceae allergy.",
     False),
    ("betula-pendula", "Betula pendula", "H%C3%A4nge-Birke", "Betula_pendula",
     "Birkengewächse", "Birch family", "Betulaceae",
     "tea", ["urinary"], "internal", [5, 6],
     "junge Blätter", "young leaves",
     "Bei bekannter Birkenpollen-Allergie meiden. Bei Nierenerkrankungen vor Anwendung Arzt befragen.",
     "Avoid if you have known birch pollen allergy. Consult a physician before use in case of kidney conditions.",
     False),
    ("urtica-dioica", "Urtica dioica", "Gro%C3%9Fe_Brennnessel", "Urtica_dioica",
     "Brennnesselgewächse", "Nettle family", "Urticaceae",
     "tea", ["urinary", "rheumatism"], "internal", [5, 6, 7, 8],
     "junge Blätter", "young leaves",
     "Frische Blätter brennen — beim Sammeln Handschuhe tragen. Bei Nierenerkrankungen Arzt befragen.",
     "Fresh leaves sting — wear gloves when collecting. Consult a physician in case of kidney conditions.",
     False),
    ("rubus-fruticosus", "Rubus fruticosus", "Brombeeren", "Rubus_fruticosus",
     "Rosengewächse", "Rose family", "Rosaceae",
     "tea", ["digestion", "skin"], "internal", [5, 6, 7],
     "junge Blätter", "young leaves",
     "Bei üblicher Anwendung keine bekannten Nebenwirkungen.",
     "No known side effects with normal use.",
     False),
    # D
    ("origanum-vulgare", "Origanum vulgare", "Echter_Dost", "Origanum_vulgare",
     "Lippenblütler", "Mint family", "Lamiaceae",
     "tea", ["digestion", "respiratory"], "internal", [7, 8],
     "blühendes Kraut", "flowering herb",
     "Ätherisches Öl in konzentrierter Form nicht für Schwangere und Kleinkinder. Als Tee oder Gewürz unbedenklich.",
     "Concentrated essential oil not suitable for pregnant women and small children. Safe as tea or spice.",
     False),
    # E
    ("althaea-officinalis", "Althaea officinalis", "Echter_Eibisch", "Althaea_officinalis",
     "Malvengewächse", "Mallow family", "Malvaceae",
     "tea", ["respiratory", "throat"], "internal", [9, 10],
     "Wurzel (Herbst)", "root (autumn)",
     "Kann die Aufnahme anderer Arzneimittel verzögern — zeitlichen Abstand einhalten.",
     "May delay absorption of other medicines — keep a time gap.",
     False),
    ("echinacea-purpurea", "Echinacea purpurea", "Purpur-Sonnenhut", "Echinacea_purpurea",
     "Korbblütler", "Daisy family", "Asteraceae",
     "tincture", ["immune", "respiratory"], "internal", [7, 8, 9],
     "blühendes Kraut", "flowering herb",
     "Bei Autoimmunerkrankungen, Tuberkulose, HIV, fortschreitenden Systemerkrankungen kontraindiziert. Nicht länger als 8 Wochen am Stück anwenden.",
     "Contraindicated in autoimmune diseases, tuberculosis, HIV, progressive systemic diseases. Do not use continuously for more than 8 weeks.",
     False),
    ("verbena-officinalis", "Verbena officinalis", "Echtes_Eisenkraut", "Verbena_officinalis",
     "Eisenkrautgewächse", "Verbena family", "Verbenaceae",
     "tea", ["nerves", "digestion"], "internal", [7, 8],
     "blühendes Kraut", "flowering herb",
     "Während Schwangerschaft meiden.",
     "Avoid during pregnancy.",
     False),
    ("gentiana-lutea", "Gentiana lutea", "Gelber_Enzian", "Gentiana_lutea",
     "Enziangewächse", "Gentian family", "Gentianaceae",
     "tea", ["digestion"], "internal", [9, 10],
     "Wurzel (Herbst, ältere Pflanzen)", "root (autumn, older plants)",
     "Bei Magengeschwüren meiden. In Deutschland strenger Naturschutz: nur Kulturware verwenden.",
     "Avoid in case of stomach ulcers. Strictly protected in Germany: use only cultivated material.",
     False),
    # F
    ("foeniculum-vulgare", "Foeniculum vulgare", "Fenchel", "Foeniculum_vulgare",
     "Doldenblütler", "Carrot family", "Apiaceae",
     "tea", ["digestion", "respiratory"], "internal", [8, 9],
     "reife Früchte", "ripe fruits",
     "In üblichen Mengen unbedenklich, klassischer Babytee. Ätherisches Öl in konzentrierter Form Vorsicht.",
     "Safe in usual amounts, classical baby tea. Caution with concentrated essential oil.",
     False),
    ("alchemilla-vulgaris", "Alchemilla vulgaris", "Gemeiner_Frauenmantel", "Alchemilla_vulgaris",
     "Rosengewächse", "Rose family", "Rosaceae",
     "tea", ["menstrual", "digestion"], "internal", [6, 7, 8],
     "blühendes Kraut", "flowering herb",
     "Bei üblicher Anwendung keine bekannten Nebenwirkungen.",
     "No known side effects with normal use.",
     False),
    # G
    ("potentilla-anserina", "Potentilla anserina", "Gemeines_Gänsefingerkraut", "Potentilla_anserina",
     "Rosengewächse", "Rose family", "Rosaceae",
     "tea", ["digestion", "menstrual"], "internal", [6, 7, 8],
     "blühendes Kraut", "flowering herb",
     "Bei üblicher Anwendung keine bekannten Nebenwirkungen.",
     "No known side effects with normal use.",
     False),
    ("ginkgo-biloba", "Ginkgo biloba", "Ginkgo", "Ginkgo_biloba",
     "Ginkgogewächse", "Ginkgo family", "Ginkgoaceae",
     "tea", ["circulation", "memory"], "internal", [9, 10],
     "Blätter (Herbst)", "leaves (autumn)",
     "Kann Blutgerinnung beeinflussen — vor Operationen und bei Blutverdünner-Einnahme Arzt befragen. Frische Samenschale kann allergische Reaktionen auslösen.",
     "May affect blood clotting — consult a physician before surgery and when taking blood thinners. Fresh seed shell may cause allergic reactions.",
     False),
    ("solidago-virgaurea", "Solidago virgaurea", "Gew%C3%B6hnliche_Goldrute", "Solidago_virgaurea",
     "Korbblütler", "Daisy family", "Asteraceae",
     "tea", ["urinary"], "internal", [7, 8, 9],
     "blühendes Kraut", "flowering herb",
     "Bei Korbblütler-Allergie meiden. Bei Nierenerkrankungen Arzt befragen. Auf ausreichende Flüssigkeitszufuhr achten.",
     "Avoid in case of Asteraceae allergy. Consult a physician for kidney conditions. Ensure adequate fluid intake.",
     False),
    ("glechoma-hederacea", "Glechoma hederacea", "Gundermann", "Glechoma_hederacea",
     "Lippenblütler", "Mint family", "Lamiaceae",
     "tea", ["respiratory", "wound"], "internal", [4, 5, 6, 7],
     "blühendes Kraut", "flowering herb",
     "Während Schwangerschaft meiden. Für Pferde giftig.",
     "Avoid during pregnancy. Toxic to horses.",
     False),
    # H
    ("rosa-canina", "Rosa canina", "Hundsrose", "Rosa_canina",
     "Rosengewächse", "Rose family", "Rosaceae",
     "tea", ["immune", "vitamin_c"], "internal", [9, 10, 11],
     "reife Hagebutten (Herbst)", "ripe rose hips (autumn)",
     "Die haarigen Samen aus den Früchten entfernen — sie reizen die Haut (\"Juckpulver\").",
     "Remove the hairy seeds from the fruits — they irritate the skin (itching powder).",
     False),
    ("hamamelis-virginiana", "Hamamelis virginiana", "Virginische_Zaubernuss", "Hamamelis_virginiana",
     "Zaubernussgewächse", "Witch-hazel family", "Hamamelidaceae",
     "tincture", ["skin", "wound"], "external", [9, 10, 11],
     "Rinde und Blätter", "bark and leaves",
     "Nur äußerlich anwenden. Bei großflächiger Anwendung auf empfindlicher Haut Vorsicht.",
     "External use only. Caution with large-area application on sensitive skin.",
     True),
    ("vaccinium-myrtillus", "Vaccinium myrtillus", "Heidelbeere", "Vaccinium_myrtillus",
     "Heidekrautgewächse", "Heath family", "Ericaceae",
     "tea", ["digestion", "vision"], "internal", [7, 8],
     "getrocknete Beeren", "dried berries",
     "Frische Beeren können in großen Mengen abführend wirken. Getrocknete Beeren wirken stopfend.",
     "Fresh berries may have a laxative effect in large amounts. Dried berries have an astringent effect.",
     False),
    ("capsella-bursa-pastoris", "Capsella bursa-pastoris", "Gew%C3%B6hnliches_Hirtent%C3%A4schel", "Capsella_bursa-pastoris",
     "Kreuzblütler", "Cabbage family", "Brassicaceae",
     "tea", ["menstrual", "wound"], "internal", [5, 6, 7, 8],
     "blühendes Kraut", "flowering herb",
     "Während Schwangerschaft meiden — wehenfördernd.",
     "Avoid during pregnancy — labour-inducing.",
     False),
    ("sambucus-nigra", "Sambucus nigra", "Schwarzer_Holunder", "Sambucus_nigra",
     "Moschuskrautgewächse", "Moschatel family", "Adoxaceae",
     "tea", ["respiratory", "fever"], "internal", [5, 6, 9, 10],
     "Blüten (Mai-Juni) und reife Beeren (Sept-Okt)", "flowers (May-June) and ripe berries (Sept-Oct)",
     "Rohe Beeren, unreife Beeren, Rinde und Blätter sind GIFTIG. Beeren immer kochen. Nur reife Beeren verwenden.",
     "Raw berries, unripe berries, bark and leaves are TOXIC. Always cook berries. Use only ripe berries.",
     False),
    ("humulus-lupulus", "Humulus lupulus", "Echter_Hopfen", "Humulus_lupulus",
     "Hanfgewächse", "Hemp family", "Cannabaceae",
     "tea", ["sleep", "nerves"], "internal", [8, 9],
     "weibliche Blütenstände (Hopfenzapfen)", "female flower clusters (hop cones)",
     "Bei Depressionen vorsichtig anwenden. Hat hormonelle Wirkungen.",
     "Use with caution in case of depression. Has hormonal effects.",
     False),
    ("tussilago-farfara", "Tussilago farfara", "Huflattich", "Tussilago_farfara",
     "Korbblütler", "Daisy family", "Asteraceae",
     "tea", ["respiratory"], "internal", [3, 4, 5],
     "Blüten (Frühjahr) und Blätter", "flowers (spring) and leaves",
     "Enthält in Spuren leberschädigende Pyrrolizidinalkaloide — Anwendung nur kurzzeitig (max 4-6 Wochen pro Jahr) und nicht in Schwangerschaft.",
     "Contains trace amounts of liver-toxic pyrrolizidine alkaloids — use only short-term (max 4-6 weeks per year) and not during pregnancy.",
     False),
    # J
    ("hypericum-perforatum", "Hypericum perforatum", "Echtes_Johanniskraut", "Hypericum_perforatum",
     "Hypericaceae", "St John's wort family", "Hypericaceae",
     "tea", ["nerves", "skin"], "both", [6, 7, 8],
     "blühendes Kraut", "flowering herb",
     "WICHTIGE WECHSELWIRKUNGEN: kann Wirkung vieler Medikamente abschwächen (Antibabypille, Blutverdünner, Antidepressiva, Immunsuppressiva u.v.m.) — bei jeder Medikamenten-Einnahme Arzt befragen. Sonnenempfindlichkeit möglich.",
     "IMPORTANT INTERACTIONS: may reduce effectiveness of many medications (birth control pill, blood thinners, antidepressants, immunosuppressants, etc.) — consult a physician when taking any medication. May cause sun sensitivity.",
     False),
    # K
    ("matricaria-chamomilla", "Matricaria chamomilla", "Echte_Kamille", "Matricaria_chamomilla",
     "Korbblütler", "Daisy family", "Asteraceae",
     "tea", ["digestion", "skin", "wound"], "both", [5, 6, 7, 8],
     "Blüten", "flowers",
     "Bei Korbblütler-Allergie meiden. Augenbäder nur unter strikter Hygiene.",
     "Avoid in case of Asteraceae allergy. Eye-baths only under strict hygiene.",
     False),
    ("tropaeolum-majus", "Tropaeolum majus", "Gro%C3%9Fe_Kapuzinerkresse", "Tropaeolum_majus",
     "Kapuzinerkressegewächse", "Nasturtium family", "Tropaeolaceae",
     "raw", ["immune", "urinary"], "internal", [6, 7, 8, 9],
     "Blätter und Blüten", "leaves and flowers",
     "Bei Magengeschwüren und Nierenerkrankungen meiden. Nicht für Kleinkinder unter 4 Jahren.",
     "Avoid in case of stomach ulcers and kidney conditions. Not for children under 4.",
     False),
    ("dipsacus-fullonum", "Dipsacus fullonum", "Wilde_Karde", "Dipsacus_fullonum",
     "Geißblattgewächse", "Honeysuckle family", "Caprifoliaceae",
     "tincture", ["joint", "skin"], "internal", [9, 10],
     "Wurzel (Herbst der zweijährigen Pflanze)", "root (autumn of the biennial plant)",
     "Traditionelle Anwendung mit eingeschränkter wissenschaftlicher Evidenz. Bei Borrelium-Verdacht keine alleinige Behandlung.",
     "Traditional use with limited scientific evidence. Not a stand-alone treatment for suspected borreliosis.",
     False),
    ("centaurea-cyanus", "Centaurea cyanus", "Kornblume", "Centaurea_cyanus",
     "Korbblütler", "Daisy family", "Asteraceae",
     "tea", ["eye", "digestion"], "both", [6, 7, 8],
     "Blüten", "flowers",
     "Bei Korbblütler-Allergie meiden. Augenbäder nur unter strikter Hygiene.",
     "Avoid in case of Asteraceae allergy. Eye-baths only under strict hygiene.",
     False),
    ("carum-carvi", "Carum carvi", "Echter_K%C3%BCmmel", "Carum_carvi",
     "Doldenblütler", "Carrot family", "Apiaceae",
     "tea", ["digestion"], "internal", [7, 8],
     "reife Früchte", "ripe fruits",
     "In üblichen Mengen als Tee und Gewürz unbedenklich.",
     "Safe in usual amounts as tea and spice.",
     False),
    # L
    ("lavandula-angustifolia", "Lavandula angustifolia", "Echter_Lavendel", "Lavandula_angustifolia",
     "Lippenblütler", "Mint family", "Lamiaceae",
     "tea", ["nerves", "sleep"], "both", [6, 7, 8],
     "Blüten", "flowers",
     "Ätherisches Öl in konzentrierter Form nicht innerlich für Kleinkinder. Selten Hautreizungen.",
     "Concentrated essential oil not for internal use in small children. Rarely causes skin irritation.",
     False),
    ("tilia-cordata", "Tilia cordata", "Winter-Linde", "Tilia_cordata",
     "Malvengewächse", "Mallow family", "Malvaceae",
     "tea", ["respiratory", "fever"], "internal", [6, 7],
     "Blüten (Hochsommer)", "flowers (midsummer)",
     "Bei längerer und häufiger Anwendung Vorsicht bei Herzproblemen.",
     "Caution with prolonged and frequent use in case of heart conditions.",
     False),
    ("taraxacum-officinale", "Taraxacum officinale", "Gew%C3%B6hnlicher_L%C3%B6wenzahn", "Taraxacum_officinale",
     "Korbblütler", "Daisy family", "Asteraceae",
     "tea", ["digestion", "urinary"], "internal", [4, 5, 6, 9, 10],
     "Wurzel (Herbst), Kraut (Frühling)", "root (autumn), herb (spring)",
     "Bei Verschluss der Gallenwege meiden. Bei Korbblütler-Allergie Vorsicht.",
     "Avoid in case of bile duct obstruction. Caution in case of Asteraceae allergy.",
     False),
    # M
    ("silybum-marianum", "Silybum marianum", "Mariendistel", "Silybum_marianum",
     "Korbblütler", "Daisy family", "Asteraceae",
     "tea", ["liver", "digestion"], "internal", [8, 9],
     "reife Früchte", "ripe fruits",
     "Bei Korbblütler-Allergie meiden. Wenig Nebenwirkungen, selten leichte Verdauungsbeschwerden.",
     "Avoid in case of Asteraceae allergy. Few side effects, rarely mild digestive complaints.",
     False),
    ("melissa-officinalis", "Melissa officinalis", "Zitronenmelisse", "Melissa_officinalis",
     "Lippenblütler", "Mint family", "Lamiaceae",
     "tea", ["nerves", "sleep", "digestion"], "internal", [6, 7, 8],
     "Blätter (vor der Blüte)", "leaves (before flowering)",
     "In üblichen Mengen sehr gut verträglich. Bei Schilddrüsenunterfunktion vorsichtig.",
     "Very well tolerated in usual amounts. Caution in case of hypothyroidism.",
     False),
    ("viscum-album", "Viscum album", "Mistel", "Viscum_album",
     "Sandelholzgewächse", "Sandalwood family", "Santalaceae",
     "tea", ["circulation"], "internal", [10, 11, 12],
     "Kraut (im Winter geerntet)", "herb (harvested in winter)",
     "Beeren sind giftig. Innerliche Anwendung nur in geprüften Fertigpräparaten. Selbst hergestellte Anwendung wegen Toxizität problematisch.",
     "Berries are toxic. Internal use only via standardised pharmaceutical preparations. Self-made preparations are problematic due to toxicity.",
     False),
    ("tanacetum-parthenium", "Tanacetum parthenium", "Mutterkraut", "Tanacetum_parthenium",
     "Korbblütler", "Daisy family", "Asteraceae",
     "tea", ["headache", "menstrual"], "internal", [6, 7, 8],
     "blühendes Kraut", "flowering herb",
     "Während Schwangerschaft meiden. Bei Korbblütler-Allergie meiden. Kann bei Kauen frischer Blätter zu Mundgeschwüren führen.",
     "Avoid during pregnancy. Avoid in case of Asteraceae allergy. Chewing fresh leaves may cause mouth ulcers.",
     False),
    # N
    ("oenothera-biennis", "Oenothera biennis", "Gew%C3%B6hnliche_Nachtkerze", "Oenothera_biennis",
     "Nachtkerzengewächse", "Evening primrose family", "Onagraceae",
     "raw", ["skin"], "both", [9, 10],
     "Samen (Herbst, daraus Öl gepresst)", "seeds (autumn, pressed for oil)",
     "Nachtkerzenöl kann selten Kopfschmerzen oder Magenbeschwerden verursachen. Bei Epilepsie Arzt befragen.",
     "Evening primrose oil may rarely cause headaches or stomach complaints. Consult a physician in case of epilepsy.",
     False),
    # O
    ("agrimonia-eupatoria", "Agrimonia eupatoria", "Kleiner_Odermennig", "Agrimonia_eupatoria",
     "Rosengewächse", "Rose family", "Rosaceae",
     "tea", ["digestion", "throat"], "both", [6, 7, 8],
     "blühendes Kraut", "flowering herb",
     "Bei üblicher Anwendung keine bekannten Nebenwirkungen. Bei Sonneneinstrahlung selten Hautreizungen.",
     "No known side effects with normal use. Rare sun sensitivity.",
     False),
    # P
    ("petroselinum-crispum", "Petroselinum crispum", "Petersilie", "Petroselinum_crispum",
     "Doldenblütler", "Carrot family", "Apiaceae",
     "raw", ["digestion", "urinary"], "internal", [5, 6, 7, 8, 9],
     "Blätter", "leaves",
     "Während Schwangerschaft große Mengen meiden. Ätherisches Öl nicht innerlich.",
     "Avoid large amounts during pregnancy. Essential oil not for internal use.",
     False),
    ("mentha-piperita", "Mentha × piperita", "Pfefferminze", "Mentha_%C3%97_piperita",
     "Lippenblütler", "Mint family", "Lamiaceae",
     "tea", ["digestion", "respiratory"], "both", [6, 7, 8],
     "Blätter (vor der Blüte)", "leaves (before flowering)",
     "Bei Sodbrennen und Gallensteinen meiden. Ätherisches Öl nicht für Säuglinge und Kleinkinder im Gesicht (Atemnot-Risiko).",
     "Avoid in case of heartburn and gallstones. Essential oil not for face application in infants and small children (risk of breathing problems).",
     False),
    # R
    ("calendula-officinalis", "Calendula officinalis", "Ringelblume", "Calendula_officinalis",
     "Korbblütler", "Daisy family", "Asteraceae",
     "salve", ["skin", "wound"], "external", [6, 7, 8, 9],
     "Blüten", "flowers",
     "Bei Korbblütler-Allergie meiden. Sehr gut verträglich.",
     "Avoid in case of Asteraceae allergy. Very well tolerated.",
     False),
    ("rosmarinus-officinalis", "Rosmarinus officinalis", "Rosmarin", "Salvia_rosmarinus",
     "Lippenblütler", "Mint family", "Lamiaceae",
     "tea", ["circulation", "digestion"], "both", [5, 6, 7, 8, 9],
     "Blätter (vor der Blüte)", "leaves (before flowering)",
     "Während Schwangerschaft große Mengen meiden. Bei Bluthochdruck Vorsicht. Ätherisches Öl nicht für Kleinkinder.",
     "Avoid large amounts during pregnancy. Caution in case of high blood pressure. Essential oil not for small children.",
     False),
    # S
    ("salvia-officinalis", "Salvia officinalis", "Echter_Salbei", "Salvia_officinalis",
     "Lippenblütler", "Mint family", "Lamiaceae",
     "tea", ["throat", "digestion"], "both", [6, 7, 8],
     "Blätter (vor der Blüte)", "leaves (before flowering)",
     "Nicht in Schwangerschaft und Stillzeit (verringert Milchbildung). Bei längerer Anwendung Vorsicht — enthält Thujon.",
     "Not during pregnancy and lactation (reduces milk production). Caution with prolonged use — contains thujone.",
     False),
    ("plantago-lanceolata", "Plantago lanceolata", "Spitzwegerich", "Plantago_lanceolata",
     "Wegerichgewächse", "Plantain family", "Plantaginaceae",
     "tea", ["respiratory", "wound"], "both", [5, 6, 7, 8],
     "Blätter (vor der Blüte)", "leaves (before flowering)",
     "Bei üblicher Anwendung keine bekannten Nebenwirkungen. Frische Blätter als Notfall-Wundauflage bei Insektenstichen.",
     "No known side effects with normal use. Fresh leaves as emergency wound dressing for insect stings.",
     False),
    ("viola-tricolor", "Viola tricolor", "Wildes_Stiefm%C3%BCtterchen", "Viola_tricolor",
     "Veilchengewächse", "Violet family", "Violaceae",
     "tea", ["skin"], "both", [4, 5, 6, 7, 8],
     "blühendes Kraut", "flowering herb",
     "Bei üblicher Anwendung keine bekannten Nebenwirkungen.",
     "No known side effects with normal use.",
     False),
    # T
    ("thymus-vulgaris", "Thymus vulgaris", "Echter_Thymian", "Thymus_vulgaris",
     "Lippenblütler", "Mint family", "Lamiaceae",
     "tea", ["respiratory"], "internal", [6, 7, 8],
     "blühendes Kraut", "flowering herb",
     "Während Schwangerschaft große Mengen meiden. Ätherisches Öl in konzentrierter Form nicht für Kleinkinder.",
     "Avoid large amounts during pregnancy. Concentrated essential oil not for small children.",
     False),
    # W
    ("salix-alba", "Salix alba", "Silber-Weide", "Salix_alba",
     "Weidengewächse", "Willow family", "Salicaceae",
     "tea", ["fever", "pain"], "internal", [3, 4, 5],
     "Rinde junger Zweige", "bark of young branches",
     "Bei Salicylat-Unverträglichkeit (Aspirin-Allergie) meiden. Nicht für Kinder unter 12 mit Fieber (Reye-Syndrom-Risiko). Bei Magengeschwüren Vorsicht.",
     "Avoid in case of salicylate intolerance (aspirin allergy). Not for children under 12 with fever (Reye syndrome risk). Caution with stomach ulcers.",
     False),
    ("crataegus-monogyna", "Crataegus monogyna", "Eingriffliger_Wei%C3%9Fdorn", "Crataegus_monogyna",
     "Rosengewächse", "Rose family", "Rosaceae",
     "tea", ["heart", "circulation"], "internal", [5, 6, 9, 10],
     "Blüten und Blätter (Mai), Beeren (Herbst)", "flowers and leaves (May), berries (autumn)",
     "Bei Herzbeschwerden niemals Selbstdiagnose — vor regelmäßiger Anwendung Arzt befragen. Sehr gut verträglich.",
     "Never self-diagnose heart conditions — consult a physician before regular use. Very well tolerated.",
     False),
    # Y
    ("hyssopus-officinalis", "Hyssopus officinalis", "Echter_Ysop", "Hyssopus_officinalis",
     "Lippenblütler", "Mint family", "Lamiaceae",
     "tea", ["respiratory", "digestion"], "internal", [7, 8],
     "blühendes Kraut", "flowering herb",
     "Während Schwangerschaft meiden. Bei Epilepsie meiden (ätherisches Öl).",
     "Avoid during pregnancy. Avoid in case of epilepsy (essential oil).",
     False),
    # === BATCH 2 — +35 plants (v0.6) ===
    ("allium-sativum", "Allium sativum", "Knoblauch", "Garlic",
     "Amaryllisgewächse", "Amaryllis family", "Amaryllidaceae",
     "raw", ["circulation", "immune"], "internal", [7, 8],
     "Zwiebel (Sommer)", "bulb (summer)",
     "Bei Blutverdünner-Einnahme oder vor Operationen Arzt befragen. Roh in großen Mengen Magenreizung möglich.",
     "Consult a physician when taking blood thinners or before surgery. Raw in large amounts may cause stomach irritation.",
     False),
    ("apium-graveolens", "Apium graveolens", "Echter_Sellerie", "Apium_graveolens",
     "Doldenblütler", "Carrot family", "Apiaceae",
     "raw", ["digestion", "urinary"], "internal", [7, 8, 9, 10],
     "Wurzel, Stiele, Samen", "root, stalks, seeds",
     "Bei Nierenerkrankungen Vorsicht. Sellerie-Allergie weit verbreitet bei Kreuzallergien.",
     "Caution in case of kidney conditions. Celery allergy common in cross-reactions.",
     False),
    ("avena-sativa", "Avena sativa", "Saat-Hafer", "Avena_sativa",
     "Süßgräser", "Grass family", "Poaceae",
     "tea", ["nerves", "skin"], "both", [7, 8],
     "grünes Haferkraut (vor der Blüte)", "green oat straw (before flowering)",
     "Bei Zöliakie unverarbeitete Haferprodukte meiden (Verunreinigung mit Weizen möglich).",
     "In case of celiac disease, avoid unprocessed oat products (wheat contamination possible).",
     False),
    ("borago-officinalis", "Borago officinalis", "Borretsch", "Borago_officinalis",
     "Raublattgewächse", "Borage family", "Boraginaceae",
     "raw", ["skin"], "internal", [6, 7, 8],
     "Blätter und Blüten (Sommer)", "leaves and flowers (summer)",
     "Enthält Pyrrolizidinalkaloide — Anwendung nur kurzzeitig (max 4-6 Wochen). In Schwangerschaft meiden. Borretschsamenöl (PA-frei) ist sicherer.",
     "Contains pyrrolizidine alkaloids — use only short-term (max 4-6 weeks). Avoid during pregnancy. Borage seed oil (PA-free) is safer.",
     False),
    ("coriandrum-sativum", "Coriandrum sativum", "Echter_Koriander", "Coriandrum_sativum",
     "Doldenblütler", "Carrot family", "Apiaceae",
     "spice", ["digestion"], "internal", [7, 8, 9],
     "Samen (Spätsommer), frische Blätter", "seeds (late summer), fresh leaves",
     "Bei Korianderallergie meiden — relativ häufig. Ansonsten als Gewürz unbedenklich.",
     "Avoid in case of coriander allergy — relatively common. Otherwise safe as spice.",
     False),
    ("cucurbita-pepo", "Cucurbita pepo", "Gartenk%C3%BCrbis", "Cucurbita_pepo",
     "Kürbisgewächse", "Cucurbit family", "Cucurbitaceae",
     "raw", ["urinary"], "internal", [9, 10],
     "Samen (Herbst, ungeschält)", "seeds (autumn, unhulled)",
     "Kürbiskerne und -kernöl bei Reizblase/Prostata-Beschwerden bewährt. Bei üblicher Anwendung sicher.",
     "Pumpkin seeds and seed oil established for irritable bladder/prostate complaints. Safe with normal use.",
     False),
    ("cydonia-oblonga", "Cydonia oblonga", "Quitte", "Quince",
     "Rosengewächse", "Rose family", "Rosaceae",
     "tea", ["digestion", "throat"], "internal", [9, 10],
     "reife Früchte (Herbst), Samen", "ripe fruits (autumn), seeds",
     "Samen enthalten Blausäureverbindungen — nicht zerkauen oder zermahlen. Schleimstoffe der Samenschale schleimlösend bei Husten.",
     "Seeds contain cyanogenic compounds — do not chew or grind. Mucilage from seed coat is soothing for cough.",
     False),
    ("cynara-scolymus", "Cynara scolymus", "Artischocke", "Artichoke",
     "Korbblütler", "Daisy family", "Asteraceae",
     "tea", ["liver", "digestion"], "internal", [7, 8, 9],
     "Blätter (vor der Blüte)", "leaves (before flowering)",
     "Bei Gallensteinen oder Verschluss der Gallenwege meiden. Bei Korbblütler-Allergie Vorsicht.",
     "Avoid in case of gallstones or bile duct obstruction. Caution in case of Asteraceae allergy.",
     False),
    ("filipendula-ulmaria", "Filipendula ulmaria", "Echtes_M%C3%A4des%C3%BC%C3%9F", "Filipendula_ulmaria",
     "Rosengewächse", "Rose family", "Rosaceae",
     "tea", ["fever", "pain"], "internal", [6, 7, 8],
     "blühendes Kraut", "flowering herb",
     "Enthält Salicylate — bei Aspirin-Allergie meiden. Nicht für Kinder unter 12 mit Fieber (Reye-Syndrom-Risiko).",
     "Contains salicylates — avoid in case of aspirin allergy. Not for children under 12 with fever (Reye syndrome risk).",
     False),
    ("fragaria-vesca", "Fragaria vesca", "Wald-Erdbeere", "Fragaria_vesca",
     "Rosengewächse", "Rose family", "Rosaceae",
     "tea", ["digestion"], "internal", [5, 6, 7, 8],
     "Blätter (vor der Blüte), reife Früchte", "leaves (before flowering), ripe fruits",
     "Bei üblicher Anwendung keine bekannten Nebenwirkungen.",
     "No known side effects with normal use.",
     False),
    ("galium-aparine", "Galium aparine", "Kletten-Labkraut", "Galium_aparine",
     "Rötegewächse", "Madder family", "Rubiaceae",
     "tea", ["lymph", "urinary"], "internal", [5, 6, 7, 8],
     "blühendes Kraut", "flowering herb",
     "Bei längerer Anwendung Vorsicht bei Diabetes (kann Blutzucker senken).",
     "Caution with prolonged use in case of diabetes (may lower blood sugar).",
     False),
    ("galium-odoratum", "Galium odoratum", "Waldmeister", "Galium_odoratum",
     "Rötegewächse", "Madder family", "Rubiaceae",
     "tea", ["nerves", "sleep"], "internal", [5, 6],
     "Kraut vor und während der Blüte", "herb before and during flowering",
     "Enthält Cumarin — in größeren Mengen kopfschmerzauslösend, leberbelastend. Klassischer Maibowle-Bestandteil in geringen Mengen.",
     "Contains coumarin — in larger amounts may cause headaches and liver strain. Classic May-wine ingredient in small amounts.",
     False),
    ("geum-urbanum", "Geum urbanum", "Echte_Nelkenwurz", "Geum_urbanum",
     "Rosengewächse", "Rose family", "Rosaceae",
     "tea", ["digestion", "throat"], "both", [9, 10],
     "Wurzel (Herbst)", "root (autumn)",
     "Bei üblicher Anwendung keine bekannten Nebenwirkungen. Riecht nach Gewürznelken (Eugenol).",
     "No known side effects with normal use. Smells like cloves (eugenol).",
     False),
    ("hedera-helix", "Hedera helix", "Gemeiner_Efeu", "Hedera_helix",
     "Araliengewächse", "Ginseng family", "Araliaceae",
     "tea", ["respiratory"], "internal", [5, 6, 7, 8],
     "Blätter", "leaves",
     "ROHE Blätter und Beeren GIFTIG. Innerlich nur als geprüftes Fertigpräparat (Efeu-Hustensaft). Bei Hautkontakt allergische Reaktionen möglich.",
     "RAW leaves and berries TOXIC. Internal use only as standardised preparation (ivy cough syrup). Skin contact may cause allergic reactions.",
     False),
    ("hippophae-rhamnoides", "Hippophae rhamnoides", "Sanddorn", "Hippophae_rhamnoides",
     "Ölweidengewächse", "Oleaster family", "Elaeagnaceae",
     "raw", ["immune", "vitamin_c"], "internal", [9, 10],
     "reife Beeren (Herbst)", "ripe berries (autumn)",
     "Sehr Vitamin-C-reich. Roh sehr sauer — meist als Saft oder Mus verarbeitet.",
     "Very rich in vitamin C. Very sour raw — usually processed as juice or pulp.",
     False),
    ("juglans-regia", "Juglans regia", "Echte_Walnuss", "Juglans_regia",
     "Walnussgewächse", "Walnut family", "Juglandaceae",
     "tea", ["skin", "digestion"], "both", [9, 10],
     "Blätter (Sommer), reife Nüsse (Herbst)", "leaves (summer), ripe nuts (autumn)",
     "Bei Nussallergie meiden. Längere innerliche Anwendung der Blätter vermeiden (Juglon-Gehalt).",
     "Avoid in case of nut allergy. Avoid prolonged internal use of leaves (juglone content).",
     False),
    ("juniperus-communis", "Juniperus communis", "Gemeiner_Wacholder", "Juniperus_communis",
     "Zypressengewächse", "Cypress family", "Cupressaceae",
     "tea", ["urinary", "digestion"], "internal", [9, 10, 11],
     "reife Beerenzapfen (Herbst)", "ripe berry cones (autumn)",
     "In Schwangerschaft und bei Nierenerkrankungen meiden. Nicht länger als 4-6 Wochen am Stück.",
     "Avoid during pregnancy and in case of kidney conditions. Do not use continuously for more than 4-6 weeks.",
     False),
    ("levisticum-officinale", "Levisticum officinale", "Liebst%C3%B6ckel", "Levisticum_officinale",
     "Doldenblütler", "Carrot family", "Apiaceae",
     "tea", ["digestion", "urinary"], "internal", [6, 7, 8, 9, 10],
     "Wurzel (Herbst), Blätter, Samen", "root (autumn), leaves, seeds",
     "Bei Nierenerkrankungen und in Schwangerschaft meiden. Auf ausreichende Flüssigkeitszufuhr achten.",
     "Avoid in case of kidney conditions and during pregnancy. Ensure adequate fluid intake.",
     False),
    ("malva-sylvestris", "Malva sylvestris", "Wilde_Malve", "Malva_sylvestris",
     "Malvengewächse", "Mallow family", "Malvaceae",
     "tea", ["respiratory", "digestion", "throat"], "both", [6, 7, 8, 9],
     "Blüten und Blätter", "flowers and leaves",
     "Sehr gut verträglich, klassischer Schleimstoff-Tee. Kann die Aufnahme anderer Arzneimittel verzögern.",
     "Very well tolerated, classical mucilage tea. May delay absorption of other medicines.",
     False),
    ("melilotus-officinalis", "Melilotus officinalis", "Echter_Steinklee", "Melilotus_officinalis",
     "Hülsenfrüchtler", "Legume family", "Fabaceae",
     "tea", ["circulation", "lymph"], "both", [6, 7, 8],
     "blühendes Kraut", "flowering herb",
     "Enthält Cumarin — bei Blutverdünner-Einnahme meiden. Bei längerer Anwendung Leberwerte kontrollieren.",
     "Contains coumarin — avoid when taking blood thinners. Monitor liver values with prolonged use.",
     False),
    ("ocimum-basilicum", "Ocimum basilicum", "Basilikum", "Ocimum_basilicum",
     "Lippenblütler", "Mint family", "Lamiaceae",
     "raw", ["digestion"], "internal", [6, 7, 8, 9],
     "frische Blätter (Sommer)", "fresh leaves (summer)",
     "In Schwangerschaft große Mengen meiden. Als Gewürz und Tee in üblichen Mengen unbedenklich.",
     "Avoid large amounts during pregnancy. Safe in usual amounts as spice and tea.",
     False),
    ("olea-europaea", "Olea europaea", "Olivenbaum", "Olea_europaea",
     "Ölbaumgewächse", "Olive family", "Oleaceae",
     "tea", ["circulation", "digestion"], "internal", [5, 6, 7, 8],
     "Blätter", "leaves",
     "Bei niedrigem Blutdruck Vorsicht (kann blutdrucksenkend wirken). Olivenöl extrem gut verträglich.",
     "Caution in case of low blood pressure (may lower blood pressure). Olive oil very well tolerated.",
     False),
    ("papaver-rhoeas", "Papaver rhoeas", "Klatschmohn", "Papaver_rhoeas",
     "Mohngewächse", "Poppy family", "Papaveraceae",
     "tea", ["nerves", "sleep"], "internal", [5, 6, 7],
     "Blüten (Frühsommer)", "flowers (early summer)",
     "Anders als Schlafmohn (P. somniferum) sehr schwach wirksam. Trotzdem bei Schwangerschaft meiden.",
     "Unlike opium poppy (P. somniferum), very mildly active. Still avoid during pregnancy.",
     False),
    ("pinus-sylvestris", "Pinus sylvestris", "Wald-Kiefer", "Pinus_sylvestris",
     "Kieferngewächse", "Pine family", "Pinaceae",
     "tea", ["respiratory"], "both", [4, 5],
     "junge Triebe (Frühjahr), Nadeln", "young shoots (spring), needles",
     "Ätherisches Kiefernnadelöl bei Asthma vorsichtig anwenden. Hautreizungen bei empfindlichen Personen möglich.",
     "Use pine needle essential oil with caution in case of asthma. Skin irritation possible in sensitive individuals.",
     False),
    ("primula-veris", "Primula veris", "Echte_Schl%C3%BCsselblume", "Primula_veris",
     "Primelgewächse", "Primrose family", "Primulaceae",
     "tea", ["respiratory"], "internal", [4, 5],
     "Blüten (Frühjahr), Wurzel (Herbst)", "flowers (spring), root (autumn)",
     "In Deutschland geschützt — nicht in der Natur sammeln. Bei Allergie gegen Primelgewächse meiden.",
     "Protected in Germany — do not collect in the wild. Avoid in case of primrose family allergy.",
     False),
    ("prunus-spinosa", "Prunus spinosa", "Schlehdorn", "Prunus_spinosa",
     "Rosengewächse", "Rose family", "Rosaceae",
     "tea", ["digestion", "immune"], "internal", [4, 5, 10, 11],
     "Blüten (April-Mai), Früchte nach Frost (Spätherbst)", "flowers (April-May), fruits after frost (late autumn)",
     "Früchte vor Frost stark adstringierend (Mund wird pelzig). Nach Frost milder und süßer.",
     "Fruits very astringent before frost (mouth becomes furry). Milder and sweeter after frost.",
     False),
    ("quercus-robur", "Quercus robur", "Stiel-Eiche", "Quercus_robur",
     "Buchengewächse", "Beech family", "Fagaceae",
     "bath", ["skin", "wound"], "external", [4, 5],
     "junge Rinde (Frühjahr)", "young bark (spring)",
     "Innerliche Anwendung nur kurzfristig (max 2 Wochen) wegen hohem Gerbstoffgehalt. Bei großflächigen Hautläsionen Arzt befragen.",
     "Internal use only short-term (max 2 weeks) due to high tannin content. Consult a physician for large skin lesions.",
     True),
    ("ribes-nigrum", "Ribes nigrum", "Schwarze_Johannisbeere", "Ribes_nigrum",
     "Stachelbeergewächse", "Gooseberry family", "Grossulariaceae",
     "tea", ["immune", "joint"], "internal", [5, 6, 7],
     "Blätter (Sommer), reife Beeren", "leaves (summer), ripe berries",
     "Beeren extrem Vitamin-C-reich. Bei üblicher Anwendung sehr gut verträglich.",
     "Berries extremely rich in vitamin C. Very well tolerated with normal use.",
     False),
    ("sanguisorba-officinalis", "Sanguisorba officinalis", "Gro%C3%9Fer_Wiesenknopf", "Sanguisorba_officinalis",
     "Rosengewächse", "Rose family", "Rosaceae",
     "tea", ["wound", "digestion"], "both", [6, 7, 8],
     "Wurzel (Herbst), Kraut (Sommer)", "root (autumn), herb (summer)",
     "Bei üblicher Anwendung keine bekannten Nebenwirkungen.",
     "No known side effects with normal use.",
     False),
    ("trigonella-foenum-graecum", "Trigonella foenum-graecum", "Bockshornklee", "Trigonella_foenum-graecum",
     "Hülsenfrüchtler", "Legume family", "Fabaceae",
     "tea", ["digestion", "skin"], "both", [7, 8],
     "Samen (Spätsommer)", "seeds (late summer)",
     "In Schwangerschaft meiden (wehenfördernd in größeren Mengen). Bei Erdnuss-/Kichererbsen-Allergie Vorsicht.",
     "Avoid during pregnancy (labour-inducing in larger amounts). Caution in case of peanut/chickpea allergy.",
     False),
    ("verbascum-densiflorum", "Verbascum densiflorum", "Gro%C3%9Fbl%C3%BCtige_K%C3%B6nigskerze", "Verbascum_densiflorum",
     "Braunwurzgewächse", "Figwort family", "Scrophulariaceae",
     "tea", ["respiratory"], "internal", [7, 8],
     "Blüten", "flowers",
     "Vor dem Trinken durch feines Tuch filtern (feine Härchen können Schleimhäute reizen). Ansonsten sehr gut verträglich.",
     "Filter through fine cloth before drinking (fine hairs may irritate mucous membranes). Otherwise very well tolerated.",
     False),
    ("veronica-officinalis", "Veronica officinalis", "Echter_Ehrenpreis", "Veronica_officinalis",
     "Wegerichgewächse", "Plantain family", "Plantaginaceae",
     "tea", ["respiratory", "skin"], "both", [6, 7, 8],
     "blühendes Kraut", "flowering herb",
     "Bei üblicher Anwendung keine bekannten Nebenwirkungen.",
     "No known side effects with normal use.",
     False),
    ("aesculus-hippocastanum", "Aesculus hippocastanum", "Gew%C3%B6hnliche_Rosskastanie", "Aesculus_hippocastanum",
     "Seifenbaumgewächse", "Soapberry family", "Sapindaceae",
     "salve", ["circulation"], "external", [9, 10],
     "reife Samen (Herbst)", "ripe seeds (autumn)",
     "ROHE Samen GIFTIG. Innerliche Anwendung nur als standardisiertes Fertigpräparat. Äußerlich für Venen-Salben sehr bewährt.",
     "RAW seeds TOXIC. Internal use only as standardised preparation. Excellent externally for vein salves.",
     True),
    ("bellis-perennis", "Bellis perennis", "Ausdauerndes_G%C3%A4nsebl%C3%BCmchen", "Bellis_perennis",
     "Korbblütler", "Daisy family", "Asteraceae",
     "tea", ["skin", "wound"], "both", [3, 4, 5, 6, 7, 8, 9, 10],
     "Blüten und junge Blätter", "flowers and young leaves",
     "Bei Korbblütler-Allergie meiden. Sehr mildes Volkskraut, ganzjährig sammelbar.",
     "Avoid in case of Asteraceae allergy. Very mild folk herb, gatherable year-round.",
     False),
    ("cichorium-intybus", "Cichorium intybus", "Gew%C3%B6hnliche_Wegwarte", "Cichorium_intybus",
     "Korbblütler", "Daisy family", "Asteraceae",
     "tea", ["digestion", "liver"], "internal", [6, 7, 8, 9, 10],
     "Wurzel (Herbst), Blätter (Sommer)", "root (autumn), leaves (summer)",
     "Bei Verschluss der Gallenwege meiden. Geröstete Wurzel als Kaffee-Ersatz.",
     "Avoid in case of bile duct obstruction. Roasted root as coffee substitute.",
     False),
    # === v0.7: Heilbäume Europa (10) ===
    ("fraxinus-excelsior", "Fraxinus excelsior", "Gemeine_Esche", "Fraxinus_excelsior",
     "Ölbaumgewächse", "Olive family", "Oleaceae",
     "tea", ["rheumatism", "urinary"], "internal", [5, 6],
     "junge Blätter, Rinde junger Zweige", "young leaves, bark of young twigs",
     "Bei bekannter Eschenallergie meiden. Innere Anwendung über längere Zeit mit Therapeut absprechen.",
     "Avoid in case of known ash allergy. Discuss prolonged internal use with a therapist.",
     False),
    ("fagus-sylvatica", "Fagus sylvatica", "Rotbuche", "Fagus_sylvatica",
     "Buchengewächse", "Beech family", "Fagaceae",
     "tea", ["skin", "digestion"], "internal", [4, 5, 9],
     "junge Blätter (Frühjahr), Bucheckern (Herbst)", "young leaves (spring), beechnuts (autumn)",
     "Rohe Bucheckern enthalten Fagin und Trimethylamin — nur in kleinen Mengen oder geröstet verwenden.",
     "Raw beechnuts contain fagin and trimethylamine — use only in small quantities or roasted.",
     False),
    ("picea-abies", "Picea abies", "Gemeine_Fichte", "Picea_abies",
     "Kieferngewächse", "Pine family", "Pinaceae",
     "tea", ["respiratory", "rheumatism"], "internal", [4, 5, 6],
     "Maiwipferl (junge Triebe), Harz", "spring shoots, resin",
     "Bei Asthma und keuchhustenartigem Husten ätherisches Öl nicht innerlich anwenden.",
     "Do not use essential oil internally in case of asthma and whooping-cough-like cough.",
     False),
    ("sorbus-aucuparia", "Sorbus aucuparia", "Eberesche", "Sorbus_aucuparia",
     "Rosengewächse", "Rose family", "Rosaceae",
     "tea", ["digestion", "urinary"], "internal", [9, 10],
     "reife Früchte (nach erstem Frost)", "ripe fruits (after first frost)",
     "Rohe Früchte enthalten Parasorbinsäure — Übelkeit/Durchfall möglich. Erhitzen oder Frost wandelt sie in unbedenkliche Sorbinsäure um.",
     "Raw fruits contain parasorbic acid — may cause nausea/diarrhea. Heating or frost converts it to harmless sorbic acid.",
     False),
    ("cornus-mas", "Cornus mas", "Kornelkirsche", "Cornus_mas",
     "Hartriegelgewächse", "Dogwood family", "Cornaceae",
     "tea", ["digestion", "immune"], "internal", [8, 9],
     "reife Früchte", "ripe fruits",
     "Bei üblicher Anwendung keine bekannten Nebenwirkungen. Steine vor Verwendung entfernen.",
     "No known side effects with normal use. Remove pits before use.",
     False),
    ("carpinus-betulus", "Carpinus betulus", "Hainbuche", "Carpinus_betulus",
     "Birkengewächse", "Birch family", "Betulaceae",
     "tea", ["nerves", "circulation"], "internal", [4, 5, 6],
     "junge Blätter, Knospen (Gemmotherapie)", "young leaves, buds (gemmotherapy)",
     "Bei üblicher Anwendung keine bekannten Nebenwirkungen.",
     "No known side effects with normal use.",
     False),
    ("castanea-sativa", "Castanea sativa", "Edelkastanie", "Castanea_sativa",
     "Buchengewächse", "Beech family", "Fagaceae",
     "tea", ["respiratory", "circulation"], "internal", [5, 6, 9, 10],
     "Blätter (Sommer), Früchte (Herbst)", "leaves (summer), fruits (autumn)",
     "Bei Nuss- oder Maronen-Allergie meiden.",
     "Avoid in case of nut or chestnut allergy.",
     False),
    ("populus-tremula", "Populus tremula", "Espe", "Populus_tremula",
     "Weidengewächse", "Willow family", "Salicaceae",
     "tea", ["rheumatism", "urinary"], "internal", [3, 4, 9],
     "Rinde, Knospen", "bark, buds",
     "Enthält Salicylate — bei Aspirin-Allergie und in der Schwangerschaft meiden.",
     "Contains salicylates — avoid in case of aspirin allergy and during pregnancy.",
     False),
    ("tilia-platyphyllos", "Tilia platyphyllos", "Sommerlinde", "Tilia_platyphyllos",
     "Malvengewächse", "Mallow family", "Malvaceae",
     "tea", ["respiratory", "nerves"], "internal", [6, 7],
     "Blüten", "flowers",
     "Bei üblicher Anwendung keine bekannten Nebenwirkungen.",
     "No known side effects with normal use.",
     False),
    ("ulmus-minor", "Ulmus minor", "Feldulme", "Ulmus_minor",
     "Ulmengewächse", "Elm family", "Ulmaceae",
     "tea", ["skin", "digestion"], "internal", [3, 4, 5],
     "innere Rinde junger Äste", "inner bark of young branches",
     "Innere Anwendung über längere Zeit mit Therapeut absprechen.",
     "Discuss prolonged internal use with a therapist.",
     False),
    # === v0.7: Vergessene Heilpflanzen (12) ===
    ("symphytum-officinale", "Symphytum officinale", "Echter_Beinwell", "Symphytum_officinale",
     "Raublattgewächse", "Borage family", "Boraginaceae",
     "salve", ["bones", "skin"], "external", [9, 10],
     "Wurzel (Herbst)", "root (autumn)",
     "ENTHÄLT PYRROLIZIDIN-ALKALOIDE (leberschädigend). Nur ÄUSSERLICH auf unverletzter Haut und kurzzeitig. NICHT innerlich, NICHT in Schwangerschaft/Stillzeit, NICHT bei Kindern.",
     "CONTAINS PYRROLIZIDINE ALKALOIDS (liver-toxic). EXTERNAL use only on unbroken skin, short-term. NOT internally, NOT during pregnancy/lactation, NOT for children.",
     True),
    ("mercurialis-annua", "Mercurialis annua", "Einj%C3%A4hriges_Bingelkraut", "Mercurialis_annua",
     "Wolfsmilchgewächse", "Spurge family", "Euphorbiaceae",
     "salve", ["skin"], "external", [6, 7, 8],
     "blühendes Kraut", "flowering herb",
     "GIFTIG bei innerer Anwendung — historisch als Abführmittel verwendet, heute obsolet. Nur äusserlich oder homöopathisch.",
     "TOXIC if taken internally — historically used as laxative, now obsolete. External or homeopathic use only.",
     True),
    ("lythrum-salicaria", "Lythrum salicaria", "Gew%C3%B6hnlicher_Blutweiderich", "Lythrum_salicaria",
     "Weiderichgewächse", "Loosestrife family", "Lythraceae",
     "tea", ["digestion"], "internal", [7, 8],
     "blühendes Kraut", "flowering herb",
     "Bei üblicher Anwendung keine bekannten Nebenwirkungen.",
     "No known side effects with normal use.",
     False),
    ("ononis-spinosa", "Ononis spinosa", "Dornige_Hauhechel", "Ononis_spinosa",
     "Hülsenfrüchtler", "Legume family", "Fabaceae",
     "tea", ["urinary"], "internal", [9, 10],
     "Wurzel (Herbst)", "root (autumn)",
     "Bei Wasseransammlungen durch Herz- oder Nierenschwäche nicht anwenden ohne ärztliche Begleitung.",
     "Do not use without medical supervision in case of fluid retention from heart or kidney insufficiency.",
     False),
    ("sempervivum-tectorum", "Sempervivum tectorum", "Dach-Hauswurz", "Sempervivum_tectorum",
     "Dickblattgewächse", "Stonecrop family", "Crassulaceae",
     "salve", ["skin"], "external", [6, 7, 8],
     "frische Blätter", "fresh leaves",
     "Bei üblicher äusserer Anwendung keine bekannten Nebenwirkungen. Innerliche Anwendung kann zu Erbrechen führen.",
     "No known side effects with normal external use. Internal use may cause vomiting.",
     True),
    ("pulsatilla-vulgaris", "Pulsatilla vulgaris", "Gemeine_K%C3%BCchenschelle", "Pulsatilla_vulgaris",
     "Hahnenfußgewächse", "Buttercup family", "Ranunculaceae",
     "salve", ["nerves"], "external", [3, 4],
     "getrocknetes blühendes Kraut", "dried flowering herb",
     "GIFTIG (Protoanemonin) in frischer Form. Nur getrocknet oder homöopathisch verwenden. In Mitteleuropa unter Naturschutz.",
     "TOXIC (protoanemonin) when fresh. Use only dried or homeopathically. Protected species in Central Europe.",
     True),
    ("pulmonaria-officinalis", "Pulmonaria officinalis", "Echtes_Lungenkraut", "Pulmonaria_officinalis",
     "Raublattgewächse", "Borage family", "Boraginaceae",
     "tea", ["respiratory"], "internal", [3, 4, 5],
     "blühendes Kraut", "flowering herb",
     "Enthält Spuren von Pyrrolizidin-Alkaloiden — nicht in Schwangerschaft/Stillzeit und nicht länger als 4-6 Wochen am Stück.",
     "Contains traces of pyrrolizidine alkaloids — avoid during pregnancy/lactation and do not use continuously for more than 4-6 weeks.",
     False),
    ("convallaria-majalis", "Convallaria majalis", "Maigl%C3%B6ckchen", "Convallaria_majalis",
     "Spargelgewächse", "Asparagus family", "Asparagaceae",
     "tincture", ["circulation"], "internal", [5, 6],
     "blühendes Kraut", "flowering herb",
     "STARK HERZWIRKSAM und GIFTIG (Convallatoxin). Nur unter ärztlicher Aufsicht oder homöopathisch. Selbstmedikation lebensgefährlich. NICHT mit Bärlauch verwechseln!",
     "STRONGLY CARDIAC ACTIVE and TOXIC (convallatoxin). Use only under medical supervision or homeopathically. Self-medication life-threatening. Do NOT confuse with wild garlic!",
     True),
    ("bistorta-officinalis", "Bistorta officinalis", "Schlangen-Kn%C3%B6terich", "Bistorta_officinalis",
     "Knöterichgewächse", "Knotweed family", "Polygonaceae",
     "tea", ["digestion"], "internal", [9, 10],
     "Wurzelstock (Herbst)", "rhizome (autumn)",
     "Bei üblicher Anwendung keine bekannten Nebenwirkungen. Gerbstoffreich — bei empfindlichem Magen kleinere Dosen.",
     "No known side effects with normal use. Tannin-rich — use smaller doses in case of sensitive stomach.",
     False),
    ("vinca-minor", "Vinca minor", "Kleines_Immergr%C3%BCn", "Vinca_minor",
     "Hundsgiftgewächse", "Dogbane family", "Apocynaceae",
     "tincture", ["circulation", "nerves"], "internal", [4, 5, 6],
     "blühendes Kraut", "flowering herb",
     "Nur standardisierte Fertigpräparate (Vincamin) verwenden. Eigenherstellung problematisch wegen Wirkstoffvariation. Während Schwangerschaft meiden.",
     "Use only standardised commercial preparations (vincamine). Self-prepared use problematic due to active-substance variation. Avoid during pregnancy.",
     False),
    ("menyanthes-trifoliata", "Menyanthes trifoliata", "Fieberklee", "Menyanthes_trifoliata",
     "Fieberkleegewächse", "Bogbean family", "Menyanthaceae",
     "tea", ["digestion"], "internal", [5, 6, 7],
     "Blätter vor der Blüte", "leaves before flowering",
     "Bei Magenschleimhautentzündung und Magengeschwüren nicht anwenden. Hohe Dosen können Übelkeit verursachen.",
     "Do not use in case of gastritis and stomach ulcers. High doses may cause nausea.",
     False),
    ("helleborus-niger", "Helleborus niger", "Schneerose", "Helleborus_niger",
     "Hahnenfußgewächse", "Buttercup family", "Ranunculaceae",
     "tincture", ["circulation"], "internal", [1, 2, 12],
     "Wurzelstock", "rhizome",
     "SEHR GIFTIG (Helleborin, Helleborein). Nur unter ärztlicher Aufsicht oder homöopathisch — niemals Selbstmedikation. In Mitteleuropa unter Naturschutz.",
     "HIGHLY TOXIC (helleborin, hellebrin). Use only under medical supervision or homeopathically — never self-medicate. Protected species in Central Europe.",
     True),
    # === v0.7: Küchenkräuter & Gewürze (12) ===
    ("anethum-graveolens", "Anethum graveolens", "Dill", "Dill",
     "Doldenblütler", "Carrot family", "Apiaceae",
     "tea", ["digestion"], "internal", [7, 8],
     "Früchte (reif), Kraut (frisch)", "fruits (ripe), herb (fresh)",
     "In üblicher Küchenmenge unbedenklich. Ätherisches Öl in konzentrierter Form nicht für Kleinkinder.",
     "Safe in normal culinary amounts. Concentrated essential oil not suitable for small children.",
     False),
    ("zingiber-officinale", "Zingiber officinale", "Ingwer", "Zingiber_officinale",
     "Ingwergewächse", "Ginger family", "Zingiberaceae",
     "tea", ["digestion", "nausea"], "internal", [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
     "Wurzelstock (frisch oder getrocknet)", "rhizome (fresh or dried)",
     "Bei Gallensteinen vor regelmäßiger Anwendung Arzt befragen. Hohe Dosen in Schwangerschaft umstritten — übliche Küchenmenge unbedenklich.",
     "Consult physician before regular use in case of gallstones. High doses controversial in pregnancy — normal culinary amounts safe.",
     False),
    ("curcuma-longa", "Curcuma longa", "Kurkuma", "Curcuma_longa",
     "Ingwergewächse", "Ginger family", "Zingiberaceae",
     "spice", ["digestion", "inflammation"], "internal", [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
     "Wurzelstock (frisch oder getrocknet, Pulver)", "rhizome (fresh or dried, powder)",
     "Bei Gallensteinen und blutverdünnenden Medikamenten Arzt befragen. Hochkonzentrierte Extrakte (Curcumin) nicht in Schwangerschaft.",
     "Consult physician in case of gallstones or anticoagulant medication. Highly concentrated extracts (curcumin) not during pregnancy.",
     False),
    ("cinnamomum-verum", "Cinnamomum verum", "Echter_Zimt", "Cinnamomum_verum",
     "Lorbeergewächse", "Laurel family", "Lauraceae",
     "spice", ["digestion", "circulation"], "internal", [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
     "getrocknete innere Rinde", "dried inner bark",
     "Ceylon-Zimt enthält wenig Cumarin und ist gegenüber Cassia-Zimt bevorzugt für regelmäßigen Verzehr. Hohe Cumarin-Dosen können die Leber belasten.",
     "Ceylon cinnamon contains little coumarin and is preferred over cassia cinnamon for regular consumption. High coumarin doses may strain the liver.",
     False),
    ("satureja-hortensis", "Satureja hortensis", "Sommer-Bohnenkraut", "Satureja_hortensis",
     "Lippenblütler", "Mint family", "Lamiaceae",
     "tea", ["digestion"], "internal", [7, 8, 9],
     "blühendes Kraut", "flowering herb",
     "In üblicher Küchenmenge unbedenklich. Ätherisches Öl nicht innerlich in Schwangerschaft.",
     "Safe in normal culinary amounts. Essential oil not internally during pregnancy.",
     False),
    ("mentha-spicata", "Mentha spicata", "Gr%C3%BCne_Minze", "Mentha_spicata",
     "Lippenblütler", "Mint family", "Lamiaceae",
     "tea", ["digestion", "respiratory"], "internal", [6, 7, 8],
     "Blätter (vor der Blüte)", "leaves (before flowering)",
     "Im Gegensatz zur Pfefferminze deutlich milder. Bei Reflux oder Sodbrennen kann jede Minze die Symptome verstärken.",
     "Notably milder than peppermint. Any mint can worsen reflux or heartburn symptoms.",
     False),
    ("vanilla-planifolia", "Vanilla planifolia", "Gew%C3%BCrzvanille", "Vanilla_planifolia",
     "Orchideengewächse", "Orchid family", "Orchidaceae",
     "spice", ["nerves"], "internal", [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
     "fermentierte unreife Kapseln", "fermented unripe pods",
     "Naturvanille unbedenklich. Vanillin-Imitate können bei Empfindlichen Hautausschlag auslösen.",
     "Natural vanilla safe. Vanillin imitations may cause skin rash in sensitive individuals.",
     False),
    ("syzygium-aromaticum", "Syzygium aromaticum", "Gew%C3%BCrznelkenbaum", "Syzygium_aromaticum",
     "Myrtengewächse", "Myrtle family", "Myrtaceae",
     "tea", ["respiratory", "dental"], "internal", [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
     "getrocknete Blütenknospen", "dried flower buds",
     "Ätherisches Nelkenöl nicht unverdünnt auf Schleimhäute. Bei Schwangerschaft und Kleinkindern Vorsicht mit konzentriertem Öl.",
     "Do not apply pure clove essential oil to mucous membranes. Use concentrated oil carefully during pregnancy and with small children.",
     False),
    ("cuminum-cyminum", "Cuminum cyminum", "Kreuzk%C3%BCmmel", "Cuminum_cyminum",
     "Doldenblütler", "Carrot family", "Apiaceae",
     "spice", ["digestion"], "internal", [7, 8],
     "reife Früchte", "ripe fruits",
     "In üblicher Küchenmenge unbedenklich. Nicht verwechseln mit Echtem Kümmel (Carum carvi).",
     "Safe in normal culinary amounts. Do not confuse with caraway (Carum carvi).",
     False),
    ("laurus-nobilis", "Laurus nobilis", "Echter_Lorbeer", "Laurus_nobilis",
     "Lorbeergewächse", "Laurel family", "Lauraceae",
     "spice", ["digestion", "respiratory"], "internal", [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
     "getrocknete Blätter, Früchte", "dried leaves, fruits",
     "Lorbeerblätter werden nicht mitgegessen — vor dem Servieren entfernen. Ätherisches Öl kann Hautreizungen auslösen.",
     "Bay leaves are not eaten — remove before serving. Essential oil may cause skin irritation.",
     False),
    ("artemisia-dracunculus", "Artemisia dracunculus", "Estragon", "Artemisia_dracunculus",
     "Korbblütler", "Daisy family", "Asteraceae",
     "spice", ["digestion"], "internal", [6, 7, 8, 9],
     "Kraut (vor der Blüte)", "herb (before flowering)",
     "In üblicher Küchenmenge unbedenklich. Ätherisches Öl enthält Methylchavicol — nicht in Schwangerschaft konzentriert anwenden.",
     "Safe in normal culinary amounts. Essential oil contains methyl chavicol — do not use concentrated during pregnancy.",
     False),
    ("pelargonium-graveolens", "Pelargonium graveolens", "Rosengeranie", "Pelargonium_graveolens",
     "Storchschnabelgewächse", "Cranesbill family", "Geraniaceae",
     "salve", ["skin", "nerves"], "external", [5, 6, 7, 8, 9],
     "Blätter", "leaves",
     "Ätherisches Öl bei empfindlicher Haut verdünnt anwenden. Bei Schwangerschaft und Kleinkindern vorsichtig.",
     "Apply essential oil diluted on sensitive skin. Use carefully during pregnancy and with small children.",
     False),
    # === v0.8 Heilen + Küche indoor (12) ===
    ("aloe-vera", "Aloe vera", "Echte_Aloe", "Aloe_vera",
     "Affodillgewächse", "Asphodel family", "Asphodelaceae",
     "salve", ["skin", "digestion"], "external", [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
     "Blattgel", "leaf gel",
     "Innere Anwendung des gelben Latex (Aloin) kann starke abführende Wirkung haben — nicht in Schwangerschaft, Stillzeit und nicht für Kinder. Nur das innere klare Gel verwenden.",
     "Internal use of the yellow latex (aloin) can cause strong laxative effects — avoid during pregnancy, lactation and for children. Use only the inner clear gel.",
     False),
    ("cymbopogon-citratus", "Cymbopogon citratus", "Zitronengras", "Cymbopogon_citratus",
     "Süßgräser", "Grass family", "Poaceae",
     "tea", ["digestion", "fever"], "internal", [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
     "Blätter, Stengel", "leaves, stalks",
     "In Küchenmenge unbedenklich. Ätherisches Öl konzentriert nicht innerlich in Schwangerschaft.",
     "Safe in culinary amounts. Concentrated essential oil not internally during pregnancy.",
     False),
    ("stevia-rebaudiana", "Stevia rebaudiana", "Stevia", "Stevia_rebaudiana",
     "Korbblütler", "Daisy family", "Asteraceae",
     "tea", ["digestion"], "internal", [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
     "Blätter", "leaves",
     "Als Süßungsmittel weltweit zugelassen. In sehr hohen Dosen wenig erforscht — übliche Süß-Mengen unbedenklich.",
     "Approved worldwide as a sweetener. Very high doses understudied — usual sweetening amounts safe.",
     False),
    ("aloysia-citrodora", "Aloysia citrodora", "Zitronenverbene", "Aloysia_citrodora",
     "Eisenkrautgewächse", "Verbena family", "Verbenaceae",
     "tea", ["digestion", "nerves"], "internal", [5, 6, 7, 8, 9, 10],
     "Blätter", "leaves",
     "Bei üblicher Anwendung keine bekannten Nebenwirkungen.",
     "No known side effects with normal use.",
     False),
    ("plectranthus-barbatus", "Plectranthus barbatus", "Harfenstrauch", "Plectranthus_barbatus",
     "Lippenblütler", "Mint family", "Lamiaceae",
     "tea", ["respiratory", "digestion"], "internal", [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
     "Blätter", "leaves",
     "Bei Herzerkrankungen und blutverdünnenden Medikamenten Arzt befragen (Forskolin-Gehalt).",
     "Consult physician in case of heart conditions or anticoagulants (forskolin content).",
     False),
    ("ocimum-tenuiflorum", "Ocimum tenuiflorum", "Tulsi", "Ocimum_tenuiflorum",
     "Lippenblütler", "Mint family", "Lamiaceae",
     "tea", ["immune", "nerves"], "internal", [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
     "Blätter, blühendes Kraut", "leaves, flowering herb",
     "Bei Schwangerschaft, Stillzeit und blutverdünnenden Medikamenten Arzt befragen.",
     "Consult physician during pregnancy, lactation or with anticoagulants.",
     False),
    ("mentha-villosa", "Mentha × villosa", "Mojito-Minze", "Mentha_%C3%97_villosa",
     "Lippenblütler", "Mint family", "Lamiaceae",
     "tea", ["digestion"], "internal", [5, 6, 7, 8, 9],
     "Blätter (vor der Blüte)", "leaves (before flowering)",
     "Wie andere Minzen — bei Reflux meiden.",
     "Like other mints — avoid in case of reflux.",
     False),
    ("pelargonium-odoratissimum", "Pelargonium odoratissimum", "Apfel-Geranie", "Pelargonium_odoratissimum",
     "Storchschnabelgewächse", "Cranesbill family", "Geraniaceae",
     "tea", ["nerves", "respiratory"], "internal", [5, 6, 7, 8, 9],
     "Blätter", "leaves",
     "Ätherisches Öl bei empfindlicher Haut verdünnt anwenden.",
     "Apply essential oil diluted on sensitive skin.",
     False),
    ("aerva-lanata", "Aerva lanata", "Polpala", "Aerva_lanata",
     "Fuchsschwanzgewächse", "Amaranth family", "Amaranthaceae",
     "tea", ["urinary"], "internal", [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
     "Kraut", "herb",
     "In der ayurvedischen Tradition für Nieren/Harnwege verwendet. Bei Nierenerkrankungen Arzt befragen.",
     "Used in Ayurvedic tradition for kidney/urinary tract. Consult physician in case of kidney conditions.",
     False),
    ("salvia-elegans", "Salvia elegans", "Ananas-Salbei", "Salvia_elegans",
     "Lippenblütler", "Mint family", "Lamiaceae",
     "tea", ["nerves", "digestion"], "internal", [6, 7, 8, 9, 10],
     "Blätter, Blüten", "leaves, flowers",
     "In üblicher Anwendung unbedenklich. Süßlich-fruchtiges Aroma.",
     "Safe in normal use. Sweet, fruity aroma.",
     False),
    ("houttuynia-cordata", "Houttuynia cordata", "Molchschwanz", "Houttuynia_cordata",
     "Eidechsenschwanzgewächse", "Lizard-tail family", "Saururaceae",
     "tea", ["immune", "respiratory"], "internal", [5, 6, 7, 8, 9],
     "Blätter, Wurzelstock", "leaves, rhizome",
     "Charakteristischer Geruch (Fischminze). Bei Schwangerschaft meiden. In Ostasien gewöhnliches Gemüse/Heilkraut.",
     "Characteristic smell (fish mint). Avoid during pregnancy. Common vegetable/herb in East Asia.",
     False),
    ("eruca-sativa", "Eruca sativa", "Rucola", "Eruca_sativa",
     "Kreuzblütler", "Mustard family", "Brassicaceae",
     "raw", ["digestion"], "internal", [3, 4, 5, 6, 9, 10],
     "Blätter (jung)", "leaves (young)",
     "Wegen Nitrat-Gehalt nicht in großen Mengen täglich. Bei Schilddrüsenerkrankungen Maß halten.",
     "Avoid large daily amounts due to nitrate content. Use in moderation in case of thyroid conditions.",
     False),
    # === v0.8 Luftreiniger (8) ===
    ("chlorophytum-comosum", "Chlorophytum comosum", "Gr%C3%BCnlilie", "Chlorophytum_comosum",
     "Spargelgewächse", "Asparagus family", "Asparagaceae",
     "raw", ["air_quality"], "external", [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
     "ganze Pflanze (dekorativ)", "whole plant (decorative)",
     "Ungiftig für Mensch und Tier. Katzen mögen die Blätter anknabbern — unbedenklich.",
     "Non-toxic for humans and animals. Cats may nibble leaves — harmless.",
     True),
    ("dracaena-trifasciata", "Dracaena trifasciata", "Bogenhanf", "Dracaena_trifasciata",
     "Spargelgewächse", "Asparagus family", "Asparagaceae",
     "raw", ["air_quality"], "external", [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
     "ganze Pflanze (dekorativ)", "whole plant (decorative)",
     "GIFTIG für Hunde und Katzen (Saponine) — Erbrechen/Speichelfluss bei Verzehr. Außer Reichweite halten.",
     "TOXIC for dogs and cats (saponins) — vomiting/salivation if eaten. Keep out of reach.",
     True),
    ("spathiphyllum-wallisii", "Spathiphyllum wallisii", "Einblatt", "Spathiphyllum_wallisii",
     "Aronstabgewächse", "Arum family", "Araceae",
     "raw", ["air_quality"], "external", [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
     "ganze Pflanze (dekorativ)", "whole plant (decorative)",
     "GIFTIG für Hunde und Katzen (Calciumoxalate) — Maulreizung, Sabbern, Schluckbeschwerden.",
     "TOXIC for dogs and cats (calcium oxalates) — mouth irritation, drooling, difficulty swallowing.",
     True),
    ("epipremnum-aureum", "Epipremnum aureum", "Efeutute", "Epipremnum_aureum",
     "Aronstabgewächse", "Arum family", "Araceae",
     "raw", ["air_quality"], "external", [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
     "ganze Pflanze (dekorativ)", "whole plant (decorative)",
     "GIFTIG für Hunde, Katzen und Menschen (Calciumoxalate). Bei Verzehr Maulreizung und Schwellung.",
     "TOXIC for dogs, cats and humans (calcium oxalates). Mouth irritation and swelling if eaten.",
     True),
    ("ficus-elastica", "Ficus elastica", "Gummibaum", "Ficus_elastica",
     "Maulbeergewächse", "Mulberry family", "Moraceae",
     "raw", ["air_quality"], "external", [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
     "ganze Pflanze (dekorativ)", "whole plant (decorative)",
     "Milchsaft leicht giftig und hautreizend. Bei Latex-Allergie meiden.",
     "Milky sap mildly toxic and skin-irritating. Avoid in case of latex allergy.",
     True),
    ("dracaena-fragrans", "Dracaena fragrans", "Drachenbaum", "Dracaena_fragrans",
     "Spargelgewächse", "Asparagus family", "Asparagaceae",
     "raw", ["air_quality"], "external", [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
     "ganze Pflanze (dekorativ)", "whole plant (decorative)",
     "GIFTIG für Hunde und Katzen (Saponine).",
     "TOXIC for dogs and cats (saponins).",
     True),
    ("aglaonema-commutatum", "Aglaonema commutatum", "Kolbenfaden", "Aglaonema_commutatum",
     "Aronstabgewächse", "Arum family", "Araceae",
     "raw", ["air_quality"], "external", [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
     "ganze Pflanze (dekorativ)", "whole plant (decorative)",
     "GIFTIG für Hunde, Katzen und Menschen (Calciumoxalate).",
     "TOXIC for dogs, cats and humans (calcium oxalates).",
     True),
    ("zamioculcas-zamiifolia", "Zamioculcas zamiifolia", "Gl%C3%BCcksfeder", "Zamioculcas_zamiifolia",
     "Aronstabgewächse", "Arum family", "Araceae",
     "raw", ["air_quality"], "external", [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
     "ganze Pflanze (dekorativ)", "whole plant (decorative)",
     "GIFTIG für Hunde, Katzen und Menschen (Calciumoxalate). Bei Hautkontakt mit Saft waschen.",
     "TOXIC for dogs, cats and humans (calcium oxalates). Wash skin after sap contact.",
     True),
    # === v0.8 Mücken-/Insekten-Abwehr (4) ===
    ("pelargonium-citrosum", "Pelargonium citrosum", "Citronella-Geranie", "Pelargonium_citrosum",
     "Storchschnabelgewächse", "Cranesbill family", "Geraniaceae",
     "raw", ["pest_control"], "external", [5, 6, 7, 8, 9],
     "Blätter (zerrieben)", "leaves (crushed)",
     "Wissenschaftlich umstrittene Wirksamkeit als Mückenschutz — Wirkung beim Zerreiben am stärksten.",
     "Mosquito-repellent effect scientifically debated — strongest when leaves are crushed.",
     True),
    ("nepeta-cataria", "Nepeta cataria", "Katzenminze", "Echte_Katzenminze",
     "Lippenblütler", "Mint family", "Lamiaceae",
     "tea", ["nerves", "pest_control"], "internal", [6, 7, 8, 9],
     "blühendes Kraut", "flowering herb",
     "Tee für Menschen sehr beruhigend. Auf Katzen wirkt Nepetalacton euphorisierend — unbedenklich.",
     "Tea has strong calming effect on humans. Nepetalactone is euphoric for cats — harmless.",
     False),
    ("tagetes-patula", "Tagetes patula", "Studentenblume", "Tagetes_patula",
     "Korbblütler", "Daisy family", "Asteraceae",
     "raw", ["pest_control"], "external", [5, 6, 7, 8, 9, 10],
     "blühende Pflanze", "flowering plant",
     "Wurzelausscheidungen wehren Nematoden ab. Bei Korbblütler-Allergie meiden.",
     "Root excretions repel nematodes. Avoid in case of Asteraceae allergy.",
     True),
    ("plectranthus-caninus", "Plectranthus caninus", "Verpiss-dich-Pflanze", "Plectranthus_ornatus",
     "Lippenblütler", "Mint family", "Lamiaceae",
     "raw", ["pest_control"], "external", [5, 6, 7, 8, 9],
     "Blätter (Geruch)", "leaves (scent)",
     "Geruch hält Katzen und Hunde fern. Hautkontakt kann reizen — nicht in Reichweite kleiner Kinder.",
     "Scent keeps cats and dogs away. Skin contact may irritate — keep out of reach of small children.",
     True),
    # === v0.8 Luftbefeuchter (3) ===
    ("dypsis-lutescens", "Dypsis lutescens", "Goldfruchtpalme", "Goldfruchtpalme",
     "Palmengewächse", "Palm family", "Arecaceae",
     "raw", ["air_quality"], "external", [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
     "ganze Pflanze (dekorativ)", "whole plant (decorative)",
     "Ungiftig für Mensch und Tier. Hohe Transpiration — gut zur Luftbefeuchtung.",
     "Non-toxic for humans and animals. High transpiration — good for humidifying air.",
     True),
    ("nephrolepis-exaltata", "Nephrolepis exaltata", "Schwertfarn", "Nephrolepis_exaltata",
     "Schwertfarngewächse", "Sword-fern family", "Nephrolepidaceae",
     "raw", ["air_quality"], "external", [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
     "ganze Pflanze (dekorativ)", "whole plant (decorative)",
     "Ungiftig für Mensch und Tier. Klassiker der NASA Clean Air Study.",
     "Non-toxic for humans and animals. Classic of the NASA Clean Air Study.",
     True),
    ("cyperus-alternifolius", "Cyperus alternifolius", "Zyperngras", "Wechselbl%C3%A4ttriges_Zyperngras",
     "Sauergrasgewächse", "Sedge family", "Cyperaceae",
     "raw", ["air_quality"], "external", [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
     "ganze Pflanze (dekorativ)", "whole plant (decorative)",
     "Ungiftig für Mensch und Tier. Braucht ständig nasse Erde / Untersetzer mit Wasser.",
     "Non-toxic for humans and animals. Needs constantly wet soil / saucer with water.",
     True),
    # === v0.8 Nacht-Sauerstoff (1) ===
    ("phalaenopsis-spp", "Phalaenopsis spp.", "Schmetterlingsorchidee", "Phalaenopsis",
     "Orchideengewächse", "Orchid family", "Orchidaceae",
     "raw", ["air_quality"], "external", [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
     "ganze Pflanze (dekorativ)", "whole plant (decorative)",
     "Ungiftig für Mensch und Tier. CAM-Photosynthese — gibt nachts Sauerstoff ab, gut fürs Schlafzimmer.",
     "Non-toxic for humans and animals. CAM photosynthesis — releases oxygen at night, good for the bedroom.",
     True),
]


def fetch_json(url):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=20) as r:
        return json.loads(r.read().decode())


def fetch_wikipedia_summary(lang, title):
    encoded = title  # already URL-encoded in PLANTS list
    url = f"https://{lang}.wikipedia.org/api/rest_v1/page/summary/{encoded}"
    try:
        return fetch_json(url)
    except Exception as e:
        return {"error": str(e), "lang": lang, "title": title}


def fetch_commons_metadata(filename):
    encoded = urllib.parse.quote(filename)
    url = f"https://commons.wikimedia.org/w/api.php?action=query&format=json&titles=File:{encoded}&prop=imageinfo&iiprop=extmetadata|url"
    try:
        return fetch_json(url)
    except Exception as e:
        return {"error": str(e)}


def extract_image_url(summary):
    if "originalimage" in summary:
        return summary["originalimage"]["source"]
    return None


def extract_filename_from_url(url):
    if not url:
        return None
    # Query-String abschneiden
    url = url.split("?")[0]
    # Commons-Thumbnail-URLs sehen so aus:
    #   .../commons/thumb/a/ab/EchterName.jpg/640px-EchterName.jpg
    # Der echte Commons-Dateiname ist das VORLETZTE Segment — das letzte
    # traegt einen "640px-"-Thumbnail-Praefix und existiert so nicht als File:.
    parts = url.split("/")
    if "thumb" in parts:
        fname = parts[-2]
    else:
        fname = parts[-1]
    # Sicherheitsnetz: einen evtl. verbliebenen "<N>px-"-Praefix entfernen.
    fname = re.sub(r"^\d+px-", "", fname)
    return urllib.parse.unquote(fname)


def parse_commons_meta(commons_response):
    pages = commons_response.get("query", {}).get("pages", {})
    for pid, page in pages.items():
        ii = page.get("imageinfo", [{}])[0]
        em = ii.get("extmetadata", {})
        artist_raw = em.get("Artist", {}).get("value", "Unknown")
        artist = re.sub("<[^>]+>", "", artist_raw).strip()
        # Deduplicate "Unknown authorUnknown author" pattern
        if artist == "Unknown authorUnknown author":
            artist = "Unknown"
        lic = em.get("LicenseShortName", {}).get("value", "Unknown")
        descurl = ii.get("descriptionurl", "")
        return {"author": artist[:120], "license": lic, "url": descurl}
    return {"author": "Unknown", "license": "Unknown", "url": ""}


def first_paragraph(text):
    """Take first meaningful paragraph (~2-4 sentences)."""
    if not text:
        return ""
    text = text.strip()
    # Take first 2-3 sentences
    sentences = re.split(r"(?<=[.!?])\s+", text)
    out = " ".join(sentences[:3])
    if len(out) > 600:
        out = out[:597] + "..."
    return out


def teaser_from_description(desc, max_len=120):
    """First sentence as teaser."""
    if not desc:
        return ""
    sentences = re.split(r"(?<=[.!?])\s+", desc.strip())
    out = sentences[0] if sentences else ""
    if len(out) > max_len:
        out = out[: max_len - 3] + "..."
    return out


def download_image(url, dest):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as r:
        with open(dest, "wb") as f:
            f.write(r.read())


def process_plant(plant_tuple):
    (slug, latin, de_title, en_title, fam_de, fam_en, fam_lat,
     def_form, def_target, def_intext, def_months,
     def_harvest_de, def_harvest_en,
     def_warn_de, def_warn_en, ext_only) = plant_tuple

    # Skip if already scraped — keeps existing manual curation intact
    out_path = os.path.join(DATA_DIR, f"{slug}.json")
    if os.path.exists(out_path):
        return f"{slug} (skip-existing)"

    de_sum = fetch_wikipedia_summary("de", de_title)
    en_sum = fetch_wikipedia_summary("en", en_title)

    img_url = extract_image_url(de_sum) or extract_image_url(en_sum)
    img_fname = extract_filename_from_url(img_url) if img_url else None

    image_meta = {"author": "Unknown", "license": "Unknown", "url": ""}
    if img_fname:
        try:
            commons = fetch_commons_metadata(img_fname)
            image_meta = parse_commons_meta(commons)
        except Exception:
            pass

    # Download image to local path
    local_img_name = f"{slug}.jpg"
    if img_url:
        dest = os.path.join(IMG_DIR, local_img_name)
        try:
            # Strip query string from download URL
            clean_url = img_url.split("?")[0]
            download_image(clean_url, dest)
        except Exception as e:
            print(f"  ! image download failed for {slug}: {e}", file=sys.stderr)

    name_de = de_sum.get("displaytitle", de_title).replace("<i>", "").replace("</i>", "") if "error" not in de_sum else de_title
    name_en = en_sum.get("displaytitle", en_title).replace("<i>", "").replace("</i>", "") if "error" not in en_sum else en_title
    # Strip HTML tags from displaytitle
    name_de = re.sub("<[^>]+>", "", name_de)
    name_en = re.sub("<[^>]+>", "", name_en)

    extract_de = de_sum.get("extract", "") if "error" not in de_sum else ""
    extract_en = en_sum.get("extract", "") if "error" not in en_sum else ""

    desc_de = first_paragraph(extract_de) or f"Beschreibung für {name_de} folgt — siehe Wikipedia-Artikel."
    desc_en = first_paragraph(extract_en) or f"Description for {name_en} pending — see Wikipedia article."

    teaser_de = teaser_from_description(desc_de) or f"{name_de} — siehe Detailseite."
    teaser_en = teaser_from_description(desc_en) or f"{name_en} — see detail page."

    de_url = de_sum.get("content_urls", {}).get("desktop", {}).get("page", f"https://de.wikipedia.org/wiki/{de_title}") if "error" not in de_sum else f"https://de.wikipedia.org/wiki/{de_title}"
    en_url = en_sum.get("content_urls", {}).get("desktop", {}).get("page", f"https://en.wikipedia.org/wiki/{en_title}") if "error" not in en_sum else f"https://en.wikipedia.org/wiki/{en_title}"

    plant_json = {
        "slug": slug,
        "names": {"de": name_de, "en": name_en, "latin": latin},
        "family": {"de": fam_de, "en": fam_en, "latin": fam_lat},
        "description": {"de": desc_de, "en": desc_en},
        "teaser": {"de": teaser_de, "en": teaser_en},
        "uses": [{
            "form": def_form,
            "target": def_target,
            "internal_external": def_intext,
            "description": {
                "de": f"Traditionelle Anwendung — siehe Wikipedia-Artikel und Fachliteratur.",
                "en": f"Traditional use — see Wikipedia article and specialist literature."
            },
            "source_ids": ["src_1"]
        }],
        "season": {
            "active_months": def_months,
            "harvest_part": {"de": def_harvest_de, "en": def_harvest_en}
        },
        "safety": {
            "warnings": {"de": def_warn_de, "en": def_warn_en},
            "external_only": ext_only
        },
        "classical_quotes": [],
        "sources": [
            {"id": "src_1", "type": "wikipedia", "title": f"{name_de} (Wikipedia DE)", "url": de_url, "accessed": TODAY},
            {"id": "src_2", "type": "wikipedia", "title": f"{name_en} (Wikipedia EN)", "url": en_url, "accessed": TODAY}
        ],
        "image": {
            "filename": local_img_name,
            "alt": {"de": f"Foto von {name_de}", "en": f"Photo of {name_en}"},
            "license": image_meta["license"] or "Unknown",
            "author": image_meta["author"] or "Unknown",
            "source_url": image_meta["url"] or ""
        }
    }

    # Allow second use entry to reference src_2
    plant_json["uses"][0]["source_ids"] = ["src_1", "src_2"]

    # Write JSON
    with open(out_path, "w") as f:
        json.dump(plant_json, f, ensure_ascii=False, indent=2)

    return slug


def main():
    os.makedirs(DATA_DIR, exist_ok=True)
    os.makedirs(IMG_DIR, exist_ok=True)

    print(f"Processing {len(PLANTS)} plants in parallel (max 8 workers)...")
    results = []
    with ThreadPoolExecutor(max_workers=8) as ex:
        futures = {ex.submit(process_plant, p): p[0] for p in PLANTS}
        for fut in as_completed(futures):
            slug = futures[fut]
            try:
                fut.result()
                print(f"  ✓ {slug}")
                results.append((slug, True))
            except Exception as e:
                print(f"  ✗ {slug}: {e}")
                results.append((slug, False))

    ok = sum(1 for _, s in results if s)
    print(f"\nDone: {ok}/{len(PLANTS)} succeeded.")


if __name__ == "__main__":
    main()
